// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAPxWbH6Khp4zT7bgqWSroq9aJDCLXc8c',
    appId: '1:817091050885:web:267516eaa3d1ba1534d8ec',
    messagingSenderId: '817091050885',
    projectId: 'fb-rev-todo',
    authDomain: 'fb-rev-todo.firebaseapp.com',
    storageBucket: 'fb-rev-todo.appspot.com',
    measurementId: 'G-70P42LVHV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnzIPYaRlSU4FK_B0PARcDmCVaNz0auVI',
    appId: '1:817091050885:android:4500c690b2b964c834d8ec',
    messagingSenderId: '817091050885',
    projectId: 'fb-rev-todo',
    storageBucket: 'fb-rev-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbIE29EZubE3j5KxNFlwSQ6etFQf1EvHo',
    appId: '1:817091050885:ios:3a587177de783d5434d8ec',
    messagingSenderId: '817091050885',
    projectId: 'fb-rev-todo',
    storageBucket: 'fb-rev-todo.appspot.com',
    iosBundleId: 'com.example.fbRevTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbIE29EZubE3j5KxNFlwSQ6etFQf1EvHo',
    appId: '1:817091050885:ios:02b08da55166521534d8ec',
    messagingSenderId: '817091050885',
    projectId: 'fb-rev-todo',
    storageBucket: 'fb-rev-todo.appspot.com',
    iosBundleId: 'com.example.fbRevTodoApp.RunnerTests',
  );
}
